global:
  scrape_interval: 5s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "192.168.0.200:9093"

rule_files:
  - "/tmp/prom/alerts/*.yml"
 
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.0.200:9090"]
  - job_name: "node"
    static_configs:
      - targets: ["192.168.0.200:9100"]
  - job_name: "MySQL"
    static_configs:
      - targets: ["192.168.0.200:9104"]
  - job_name: "blackbox"
    static_configs:
      - targets: ["192.168.0.200:9105"]
